version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.spring
    image: proweb-v01-app
    container_name: proweb-v01-app
    ports:
      - "${SERVER_PORT:-8013}:${SERVER_PORT:-8013}"
    environment:
      - SPRING_PROFILES_ACTIVE=v01
      - SERVER_PORT=${SERVER_PORT:-8013}
      - SERVER_CONTEXT_PATH=/
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/h2db/v01-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;WRITE_DELAY=0;LOCK_TIMEOUT=10000
      - SPRING_DATASOURCE_DRIVER=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=${H2_DB_PASSWORD:-v01password}
      - SPRING_JPA_DIALECT=org.hibernate.dialect.H2Dialect
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - H2_CONSOLE_ENABLED=true
      - LOG_LEVEL=INFO
      - LOG_LEVEL_WEB=WARN
      - JAVA_OPTS=-Xmx512m -Xms256m -Djava.security.egd=file:/dev/./urandom
      - TZ=America/Sao_Paulo
    volumes:
      - ./h2data/v01:/data/h2db:rw
    restart: unless-stopped
    user: "1000:1000"
    networks:
      - proweb-v01-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${SERVER_PORT:-8013}/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 45s
    depends_on: []
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  proweb-v01-network:
    driver: bridge
    name: proweb-v01-network

volumes:
  h2data:
    driver: local
