# Configuração específica para DESENVOLVIMENTO
server:
  port: 8021
  servlet:
    context-path: /
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ${H2_DB_PASSWORD:devpassword}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
      
  jpa:
    hibernate:
      ddl-auto: create-drop  # Recria o banco a cada restart
    show-sql: true          # Mostra SQL no console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        '[format_sql]': true    # Formata SQL no console
        
  h2:
    console:
      enabled: true         # Console H2 habilitado
      path: /h2-console
      
logging:
  level:
    '[com.example.deploy]': DEBUG    # Log detalhado da aplicação
    '[org.springframework.web]': INFO
    '[org.hibernate.SQL]': DEBUG     # SQL queries
    '[org.hibernate.type]': TRACE    # Parâmetros SQL
    root: INFO
    
management:
  endpoints:
    web:
      exposure:
        include: '*'        # Todos os endpoints do actuator
  endpoint:
    health:
      show-details: always
    env:
      show-values: always