# Configuração alternativa para produção com H2 em memória
# Para casos onde há problemas de permissão com arquivos

server:
  port: 8013
  servlet:
    context-path: /
  forward-headers-strategy: framework
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  datasource:
    # H2 em memória - não requer permissões de arquivo
    url: jdbc:h2:mem:prowebv01db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ${H2_DB_PASSWORD:defaultpassword}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: create-drop  # Recria tabelas a cada inicialização
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        '[format_sql]': false
        '[use_sql_comments]': false
        '[generate_statistics]': false
        cache:
          '[use_second_level_cache]': false
  h2:
    console:
      enabled: false
  
logging:
  level:
    '[com.example.deploy]': INFO
    '[org.springframework.web]': WARN
    '[org.hibernate.SQL]': WARN
    '[org.hibernate.type.descriptor.sql.BasicBinder]': WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"