name: Hostinger Workflow

on:
  push:
    branches:
      - main
  # workflow_dispatch:
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v2
        with:
          java-version: "24"
          distribution: "temurin"

      - name: Build and Test with Maven
        run: mvn clean install -Dspring.profiles.active=test

      - name: Save test reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Prepare files Spring Boot
        run: |
          mkdir -p ProgramacaoWebSpringBoot
          cp -r target ProgramacaoWebSpringBoot
          cp docker-compose.yml ProgramacaoWebSpringBoot/
          cp Dockerfile.spring ProgramacaoWebSpringBoot/

      - name: deletando no servidor
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.sftp_host }}
          username: ${{ secrets.sftp_user }}
          key: ${{ secrets.sftp_private_key }}
          port: ${{ secrets.sftp_port }}
          script: |
            rm -rf ProgramacaoWebSpringBoot/

      - name: Copy files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.sftp_host }}
          username: ${{ secrets.sftp_user }}
          key: ${{ secrets.sftp_private_key }}
          port: ${{ secrets.sftp_port }}
          source: "./ProgramacaoWebSpringBoot"
          target: "/root"
          overwrite: true

      - name: executing remote ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.sftp_host }}
          username: ${{ secrets.sftp_user }}
          key: ${{ secrets.sftp_private_key }}
          port: ${{ secrets.sftp_port }}
          envs: H2_DB_PASSWORD
          script: |
            cd ProgramacaoWebSpringBoot
            H2_DB_PASSWORD="${{ secrets.H2_DB_PASSWORD }}" docker compose up -d --build
            H2_DB_PASSWORD="${{ secrets.H2_DB_PASSWORD }}" docker compose restart
            docker compose restart
